// AUTO-GENERATED by scripts/fetch-dotfiles.mjs — do not edit by hand.
// Run `npm run fetch-dotfiles` to refresh. Runs automatically before `npm run build`.

import type { DotfileNode } from '@/types';

export const DOTFILES_REPO = 'https://github.com/bopeng95/dotfiles';

export const dotfiles: DotfileNode[] = [
  {
    name: 'dot_aliases',
    path: 'home/dot_aliases',
    size: 805,
  },
  {
    name: 'dot_config',
    children: [
      {
        name: 'bat',
        children: [
          {
            name: 'config',
            path: 'home/dot_config/bat/config',
            size: 1122,
          },
        ],
      },
      {
        name: 'eza',
        children: [
          {
            name: 'theme.yml',
            path: 'home/dot_config/eza/theme.yml',
            size: 3092,
          },
        ],
      },
      {
        name: 'nvim',
        children: [
          {
            name: 'dot_gitignore',
            path: 'home/dot_config/nvim/dot_gitignore',
            size: 51,
          },
          {
            name: 'dot_neoconf.json',
            path: 'home/dot_config/nvim/dot_neoconf.json',
            size: 183,
          },
          {
            name: 'init.lua',
            path: 'home/dot_config/nvim/init.lua',
            size: 72,
          },
          {
            name: 'lazy-lock.json',
            path: 'home/dot_config/nvim/lazy-lock.json',
            size: 3923,
          },
          {
            name: 'lazyvim.json',
            path: 'home/dot_config/nvim/lazyvim.json',
            size: 427,
          },
          {
            name: 'lua',
            children: [
              {
                name: 'config',
                children: [
                  {
                    name: 'autocmds.lua',
                    path: 'home/dot_config/nvim/lua/config/autocmds.lua',
                    size: 424,
                  },
                  {
                    name: 'keymaps.lua',
                    path: 'home/dot_config/nvim/lua/config/keymaps.lua',
                    size: 209,
                  },
                  {
                    name: 'lazy.lua',
                    path: 'home/dot_config/nvim/lua/config/lazy.lua',
                    size: 1856,
                  },
                  {
                    name: 'options.lua',
                    path: 'home/dot_config/nvim/lua/config/options.lua',
                    size: 212,
                  },
                ],
              },
              {
                name: 'plugins',
                children: [
                  {
                    name: 'colorscheme.lua',
                    path: 'home/dot_config/nvim/lua/plugins/colorscheme.lua',
                    size: 624,
                  },
                  {
                    name: 'example.lua',
                    path: 'home/dot_config/nvim/lua/plugins/example.lua',
                    size: 5295,
                  },
                  {
                    name: 'navigator.lua',
                    path: 'home/dot_config/nvim/lua/plugins/navigator.lua',
                    size: 1137,
                  },
                  {
                    name: 'oil.lua',
                    path: 'home/dot_config/nvim/lua/plugins/oil.lua',
                    size: 787,
                  },
                ],
              },
            ],
          },
          {
            name: 'stylua.toml',
            path: 'home/dot_config/nvim/stylua.toml',
            size: 58,
          },
        ],
      },
      {
        name: 'starship',
        children: [
          {
            name: 'starship.toml',
            path: 'home/dot_config/starship/starship.toml',
            size: 2810,
          },
        ],
      },
      {
        name: 'wezterm',
        children: [
          {
            name: 'wezterm.lua',
            path: 'home/dot_config/wezterm/wezterm.lua',
            size: 793,
          },
        ],
      },
      {
        name: 'yazi',
        children: [
          {
            name: 'package.toml',
            path: 'home/dot_config/yazi/package.toml',
            size: 135,
          },
          {
            name: 'theme.toml',
            path: 'home/dot_config/yazi/theme.toml',
            size: 36,
          },
          {
            name: 'yazi.toml',
            path: 'home/dot_config/yazi/yazi.toml',
            size: 7544,
          },
        ],
      },
    ],
  },
  {
    name: 'dot_tmux.conf',
    path: 'home/dot_tmux.conf',
    size: 2064,
  },
  {
    name: 'dot_tmux',
    children: [
      {
        name: 'themes',
        children: [
          {
            name: 'catppuccin.conf',
            path: 'home/dot_tmux/themes/catppuccin.conf',
            size: 2588,
          },
        ],
      },
    ],
  },
  {
    name: 'dot_zprofile',
    path: 'home/dot_zprofile',
    size: 509,
  },
  {
    name: 'dot_zshrc',
    path: 'home/dot_zshrc',
    size: 248,
  },
  {
    name: 'vscode',
    children: [
      {
        name: 'keybindings.json',
        path: 'home/vscode/keybindings.json',
        size: 5781,
      },
      {
        name: 'settings.json',
        path: 'home/vscode/settings.json',
        size: 996,
      },
    ],
  },
];
